default:
  stackName: sat-api-v3

  system_bucket: change-me 

  tags:
    project: sat-api

  capabilities:
    - CAPABILITY_IAM

  es:
    name: es6
    version: '6.0'
    instanceCount: 1
    instanceType: t2.small.elasticsearch
    volumeSize: 35 

  apis:
    - name: stac

  lambdas:
    landsat:
      source: 'node_modules/@sat-utils/landsat/dist/'
      handler: index.handler
      timeout: 300
      memory: 1024
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    sentinel:
      source: 'node_modules/@sat-utils/sentinel/dist/'
      handler: index.handler
      timeout: 300
      memory: 512
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    ingest:
      source: 'node_modules/@sat-utils/ingest/dist/'
      handler: index.handler
      timeout: 300
      memory: 1024
      envs:
        bucket: '{{system_bucket}}'
        prefix: '{{stackName}}'
    manager:
      source: 'node_modules/@sat-utils/manager/dist/'
      handler: index.handler
      timeout: 300
      memory: 192
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
        ES_ARN: "!GetAtt {{es.name}}Domain.DomainArn"
        ROLE_ARN: "!GetAtt LambdaRole.Arn"
        BUCKET: "{{system_bucket}}"
    api:
      source: 'node_modules/@sat-utils/api/dist/'
      handler: index.handler
      timeout: 100
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
      apiGateway:
        - api: stac
          path: '{proxy+}'
          method: get
          cors: true
